---
title: "EDA_BRCA_project"
author: "Tomas Meade, Chris Harden, Anna Golab"
date: "21/02/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(TCGAbiolinks)
library(SummarizedExperiment)
library(ggplot2)
library(ComplexHeatmap)

#Projects available
GDCprojects <- getGDCprojects()
head(GDCprojects[c("project_id", "name")])

#BRCA project
TCGAbiolinks:::getProjectSummary("TCGA-BRCA")
```

1. Clinical Data Analysis. 

vital status
radiation

connect with survival analysis. 
```{r}
#Clinical Data
clinical_data <- GDCquery_clinic("TCGA-BRCA","clinical")
p <- ggplot(clinical_data, aes(x=age_at_index, color=gender)) +
  geom_histogram(fill="white", position="dodge")+
  theme(legend.position="top")
p
```

```{r}
b<-ggplot(clinical_data, aes(x=ethnicity)) + 
  geom_bar(color="black", fill="white")
b
```

```{r}
b<-ggplot(clinical_data, aes(x=race)) + 
  geom_bar(color="black", fill="white") +
  theme(axis.text.x = element_text(angle = 50, hjust=1))
b
```


```{r}
c<- ggplot(clinical_data, aes(x = ajcc_pathologic_stage, color = vital_status))+
  geom_bar(fill="white", position="dodge") +
  theme(axis.text.x = element_text(angle = 50, hjust=1))
c
```

2. HER 2 amplifications are severe cause of cancer. proof. talk about ER and PR still needed. 
```{r}
#Gene Level Copy Number Scores query.
# query <- GDCquery(
#   project = "TCGA-BRCA",
#   data.category = "Copy Number Variation",
#   data.type = "Gene Level Copy Number Scores")
# 
# GDCdownload(query = query)
# brca_data <- GDCprepare(query)
# saveRDS(object = brca_data,
#         file = "brca_data.RDS",
#         compress = FALSE)
brca_data <- readRDS(file = "brca_data.RDS")

#Histogram of Copy Number Score for HER2.
library(data.table)
HER2_CNS <- transpose(as.data.frame(brca_data[substr(brca_data$`Gene Symbol`,1,15)=='ENSG00000141736',4:1109]))

plot(density(HER2_CNS$V1))
```

3. What are other genes that are mutated for our patients? which can be linked to higher survival? 
```{r}
# Mutations of listed genes
mut <- GDCquery_Maf(tumor = "BRCA", pipelines = "mutect")
clin <- GDCquery_clinic("TCGA-BRCA","clinical")
clin <- clin[,c("bcr_patient_barcode","disease","gender","race","vital_status")]
TCGAvisualize_oncoprint(mut = mut, genes = mut$Hugo_Symbol[1:20],
                        filename = "oncoprint.pdf",
                        annotation = clin,
                        color=c("background"="#CCCCCC","DEL"="purple","INS"="yellow","SNP"="brown"),
                        rows.font.size=10,
                        width = 5,
                        heatmap.legend.side = "right",
                        dist.col = 0,
                        label.font.size = 10)

#clinical_brca_data <- TCGAquery_clinic("brca","clinical_patient")
```

```{r}

# Mutation and Clinical Data Plot with Genes of Interest

mut <- GDCquery_Maf(tumor = "BRCA", pipelines = "mutect")
clin <- GDCquery_clinic("TCGA-BRCA","clinical")
clin <- clin[,c("bcr_patient_barcode","disease","gender","race","vital_status")]

genes = mut$Hugo_Symbol[mut$Hugo_Symbol %in% c("PTEN", 
                                               "TP53", 
                                               "HRAS", 
                                               "KRAS", 
                                               "NRAS", 
                                               "ERBB2", 
                                               "PIK3CA", 
                                               "POLE")]

TCGAvisualize_oncoprint(mut = mut, genes = genes,
                        filename = "oncoprint.pdf",
                        annotation = clin,
                        color=c("background"="#CCCCCC","DEL"="purple","INS"="yellow","SNP"="brown"),
                        rows.font.size=10,
                        width = 5,
                        heatmap.legend.side = "right",
                        dist.col = 0,
                        label.font.size = 10)
```


4. Idea -> build clusters that can help predicting survival rates. Tomas has some code built. 

```{r}

query <- GDCquery(project = "TCGA-BRCA",
             data.category = "Copy Number Variation",
             data.type = "Gene Level Copy Number Scores",              
             access = "open")

GDCdownload(query)
scores <- GDCprepare(query)
head(scores)

library(dplyr)
focal_scores <- select(scores, -c("Gene ID", "Cytoband"))

```


```{r}

# Clustering with just focal scores

# Remove metadata from the first 3 columns
scores.matrix <- scores %>% dplyr::select(-c(1:3)) %>% as.matrix

rownames(scores.matrix) <- paste0(scores$`Gene Symbol`,"_", scores$Cytoband)

# Gain in more than 250 samples
gain.more.than.twohundred.samples <- which(rowSums(scores.matrix == 1) > 250)

# Loss in more than 185 samples
loss.more.than.twohundred.samples <- which(rowSums(scores.matrix == -1) > 185)

lines.selected <- c(gain.more.than.twohundred.samples,loss.more.than.twohundred.samples)

# Plot of clustered heatmap

# Uses hclust function by default with agglomerative clustering and euclidean distance
Heatmap(scores.matrix[lines.selected,],
        column_title = "Samples",
        row_title = "Genes",
        show_column_names = FALSE, 
        show_row_names = TRUE,
        row_names_gp = gpar(fontsize = 8),
        col = circlize::colorRamp2(c(-1,0,1), colors = c("black","dodgerblue","yellow")))

```




```{r}

# Clustering with more features

# Remove metadata from the first 3 columns

library(stringi)
library(data.table)


# Cleaning and Merging clinical focal scores data

focal_scores_t <- transpose(focal_scores)

colnames(focal_scores_t) <- focal_scores$`Gene Symbol`

focal_scores_t$submitter_id <- colnames(focal_scores)

focal_scores_t <- focal_scores_t[-1,]

focal_scores_t$submitter_id <- stri_sub(focal_scores_t$submitter_id, 1,-17)

focal_scores_t <- focal_scores_t[!duplicated(focal_scores_t$submitter_id),]

# Gain in more than 250 samples
gain.more.than.twohundred.samples <- which(colSums(focal_scores_t == 1) > 250)

# Loss in more than 185 samples
loss.more.than.twohundred.samples <- which(colSums(focal_scores_t == -1) > 185)

lines.selected <- c(gain.more.than.twohundred.samples,loss.more.than.twohundred.samples)

scores_select_genes <- focal_scores_t[, lines.selected]

scores_select_genes$ENSG00000141736 <- focal_scores_t$ENSG00000141736

scores_select_genes$submitter_id <- focal_scores_t$submitter_id

clin <- GDCquery_clinic("TCGA-BRCA","clinical")
clin <- clin[,c("submitter_id","gender","race","vital_status", "days_to_death", "days_to_last_follow_up", "age_at_index", "ajcc_pathologic_stage")]

data <- merge(scores_select_genes, clin, by = "submitter_id")

# Clustering

# Uses hclust function by default with agglomerative clustering and grower distance

library(cluster)

x <- data[, 2:ncol(data)]

library(dplyr)

X <- x%>%mutate_if(is.character, as.factor)
str(X)

# calculate distance
d_dist <- daisy(X, metric = "grower")

# hierarchical clustering
hc <- hclust(d_dist, method = "complete")

# dendrogram 
plot(hc, labels=FALSE)
rect.hclust(hc, k=5, border="red")

# choose k, number of clusters 
cluster <- cutree(hc, k=5)

# add cluster to original data 
data <- cbind(data, as.factor(cluster))

nrow(data)


```







```{r}

unique(data$ajcc_pathologic_stage)

stage1 <- data[data$ajcc_pathologic_stage == "Stage I" | data$ajcc_pathologic_stage == "Stage IA" | data$ajcc_pathologic_stage == "Stage IB", ]
  
TCGAanalyze_survival(stage1,
                     clusterCol= "ENSG00000141736",
                     risk.table = FALSE,
                     conf.int = FALSE,
                     color = c("Dark2"))

stage2 <- data[data$ajcc_pathologic_stage == "Stage II" | data$ajcc_pathologic_stage == "Stage IIA" | data$ajcc_pathologic_stage == "Stage IIB", ]
  
TCGAanalyze_survival(stage2,
                     clusterCol= "ENSG00000141736",
                     risk.table = FALSE,
                     conf.int = FALSE,
                     color = c("Dark2"))

stage3 <- data[data$ajcc_pathologic_stage == "Stage III" | data$ajcc_pathologic_stage == "Stage IIIA" | data$ajcc_pathologic_stage == "Stage IIIB" | data$ajcc_pathologic_stage == "Stage IIIC", ]
  
TCGAanalyze_survival(stage3,
                     clusterCol= "ENSG00000141736",
                     risk.table = FALSE,
                     conf.int = FALSE,
                     color = c("Dark2"))

stage4 <- data[data$ajcc_pathologic_stage == "Stage IV", ]
  
TCGAanalyze_survival(stage4,
                     clusterCol= "ENSG00000141736",
                     risk.table = FALSE,
                     conf.int = FALSE,
                     color = c("Dark2"))

stage5 <- data[data$ajcc_pathologic_stage == "Stage X", ]
  
TCGAanalyze_survival(stage5,
                     clusterCol= "ENSG00000141736",
                     risk.table = FALSE,
                     conf.int = FALSE,
                     color = c("Dark2"))


```


```{r}

# ER and PR

library(readr)
er_pr <- read_tsv("nationwidechildrens.org_clinical_patient_brca.txt")

er_pr$days_to_death <- er_pr$death_days_to

er_pr$days_to_last_follow_up <- er_pr$last_contact_days_to


```




